# fly.toml app configuration file for review-tool

app = 'review-tool'
primary_region = 'ewr'

[build]

[env]
  PORT    = "3000"
  DB_PATH = "/data/review.db"

[http_service]
  internal_port        = 3000
  force_https          = true
  auto_stop_machines   = 'stop'
  auto_start_machines  = true
  min_machines_running = 1
  processes            = ['app']

[[mounts]]
  source      = "review_data"
  destination = "/data"

[[vm]]
  memory    = '256mb'
  cpu_kind  = 'shared'
  cpus      = 1
